<a href="https://colab.research.google.com/github/Mayank-MSJ-Singh/Nanam1/blob/main/Naman.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [5]:
import pandas as pd         #Import Pandas
import numpy as np
d = pd.read_csv('/content/drive/MyDrive/Copy of Data.csv')      #Load Data

d_copy = d.copy()       #Copy Data

l=[3,4,6,9,10,11,14,15,16,17,18,19,20,23,24,25,26,30,31]
d_copy.drop(d_copy.columns[l], axis=1, inplace=True)        #Remove Columns

#Rename Columns
d_copy.rename(columns={'CMPLNT_NUM' : 'cmp_no', 'CMPLNT_FR_DT' : 'cmp_dt', 'CMPLNT_FR_TM' : 'cmp_tm', 'ADDR_PCT_CD' : 'police_station', 'KY_CD' : 'crime_code', 'OFNS_DESC' : 'crime_name', 'LAW_CAT_CD' : 'crime_level', 'BORO_NM': 'city_name', 'X_COORD_CD' : 'x_cord', 'Y_COORD_CD' : 'y cord', 'VIC_AGE_GROUP' :'vic_age_group', 'VIC_RACE':' vic_cast', 'VIC_SEX':'vic_sex'}, inplace=True)

columns_list = d_copy.columns.tolist()      #list columns 

d_copy = d_copy[~d_copy['city_name'].isin(['nan'])]
d_copy = d_copy[~d_copy['police_station'].isin(['nan'])]
d_copy = d_copy[d_copy['vic_age_group'].isin(['<18', '18-24','25-44','45-64','65+'])]       #Remove Unknown Values
d_copy = d_copy[~d_copy[' vic_cast'].isin(['UNKNOWN'])]
d_copy = d_copy[d_copy['vic_sex'].isin(['M','F'])]



a = np.ones(5158938)
d_copy['result'] = a

d_copy['cmp_tm_hr'] = d_copy['cmp_tm'].str[0:2]
d_copy['cmp_tm_min'] = d_copy['cmp_tm'].str[3:5]
d_copy['cmp_tm_sec'] = d_copy['cmp_tm'].str[6:8]
d_copy['cmp_dt_month'] = d_copy['cmp_dt'].str[0:2]
d_copy['cmp_dt_day'] = d_copy['cmp_dt'].str[3:5]
d_copy['cmp_dt_year'] = d_copy['cmp_dt'].str[6:10]

columns_list = d_copy.columns.tolist() 

d_copy['cmp_tm_hr'] = d_copy['cmp_tm_hr'].fillna(0).astype(int)
d_copy['cmp_tm_min'] = d_copy['cmp_tm_min'].fillna(0).astype(int)
d_copy['cmp_tm_sec'] = d_copy['cmp_tm_sec'].fillna(0).astype(int)
d_copy['cmp_dt_day'] = d_copy['cmp_dt_day'].fillna(0).astype(int)
d_copy['cmp_dt_month'] = d_copy['cmp_dt_month'].fillna(0).astype(int)
d_copy['cmp_dt_year'] = d_copy['cmp_dt_year'].fillna(0).astype(int)

d_copy['crime_name'], unique_values = pd.factorize(d_copy['crime_name'])
d_copy['crime_level'], unique_values = pd.factorize(d_copy['crime_level'])
d_copy['city_name'], unique_values = pd.factorize(d_copy['city_name'])
d_copy['vic_age_group'], unique_values = pd.factorize(d_copy['vic_age_group'])
d_copy[' vic_cast'], unique_values = pd.factorize(d_copy[' vic_cast'])
d_copy['vic_sex'], unique_values = pd.factorize(d_copy['vic_sex'])

new_order=['cmp_no','cmp_dt_day','cmp_dt_month', 'cmp_dt_year'  , 'cmp_tm_hr', 'cmp_tm_min', 'cmp_tm_sec',  'x_cord', 'y cord', 'Latitude', 'Longitude', 'Lat_Lon', 'vic_age_group', ' vic_cast',
       'vic_sex', 'city_name', 'police_station', 'crime_level','crime_code',  'crime_name',   'result', 'cmp_dt_Month', 'cmp_dt_Year', 'cmp_dt', 'cmp_tm']
d_copy = d_copy.reindex(columns=new_order)

d_copy.drop(columns=['cmp_dt_Month'], inplace=True)
d_copy.drop(columns=['cmp_dt_Year'], inplace=True)
d_copy.drop(columns=['cmp_dt'], inplace=True)
d_copy.drop(columns=['cmp_tm'], inplace=True)
d_copy.drop(columns=['Lat_Lon'], inplace=True)

cols = d_copy.columns.tolist()
for i in cols:

    d_copy = d_copy[~d_copy[i].isin([-1])]
    d_copy = d_copy[~d_copy[i].isin(['nan'])]

print(d_copy)

<ipython-input-5-684660a943fa>:3: DtypeWarning: Columns (18,20) have mixed types. Specify dtype option on import or set low_memory=False.
  d = pd.read_csv('/content/drive/MyDrive/Copy of Data.csv')      #Load Data

            cmp_no  cmp_dt_day  cmp_dt_month  cmp_dt_year  cmp_tm_hr  \
2        509837549          15            12         2019         18
7        134037758          26            12         2019         20
8        855385879          26            12         2019         19
9        241602326          25            12         2019         23
14       249276017          20            12         2019         14
...            ...         ...           ...          ...        ...
7825494  744350707          17            12         2018          3
7825495  380927470           5             6         2018         23
7825496  502083804          10             2         2018          8
7825497  609916130          11            12         2018          7
7825498  766425924          10             5         2018         11

         cmp_tm_min  cmp_tm_sec     x_cord    y cord   Latitude  Longitude  \
2                45           0  1034178.0  209758.0  40.742281 -73.819824
7                 0           0  1054394.0  162186.0  40.611570 -73.747365
8                57           0  1007027.0  245405.0  40.840234 -73.917684
9                 0           0   987147.0  220853.0  40.772875 -73.989542
14                0           0  1008690.0  238862.0  40.822271 -73.911698
...             ...         ...        ...       ...        ...        ...
7825494           0           0  1026486.0  262591.0  40.887333 -73.847250
7825495          30           0  1018029.0  240747.0  40.827414 -73.877946
7825496          30           0  1010861.0  243330.0  40.834528 -73.903836
7825497          30           0  1001322.0  235045.0  40.811812 -73.938329
7825498          30           0  1016138.0  214586.0  40.755616 -73.884903

         vic_age_group   vic_cast  vic_sex  city_name  police_station  \
2                    0          0        0          0           109.0
7                    0          0        0          0           101.0
8                    1          1        0          1            44.0
9                    2          1        1          2            20.0
14                   3          2        1          1            42.0
...                ...        ...      ...        ...             ...
7825494              0          0        0          1            47.0
7825495              0          1        1          1            43.0
7825496              2          1        0          1            42.0
7825497              3          1        1          2            32.0
7825498              0          0        0          0           115.0

         crime_level  crime_code  crime_name  result
2                  0         578           0     1.0
7                  2         341           2     1.0
8                  2         361           3     1.0
9                  2         341           2     1.0
14                 1         106           4     1.0
...              ...         ...         ...     ...
7825494            2         348          13     1.0
7825495            1         110          10     1.0
7825496            2         341           2     1.0
7825497            2         344           5     1.0
7825498            2         341           2     1.0

[5142662 rows x 20 columns]

In [6]:
import tensorflow as tf
from sklearn.model_selection import train_test_split

In [7]:
random_subset = d_copy.sample(n=60)
print(d_copy.dtypes)
# print the random subset
print(random_subset)

cmp_no              int64
cmp_dt_day          int64
cmp_dt_month        int64
cmp_dt_year         int64
cmp_tm_hr           int64
cmp_tm_min          int64
cmp_tm_sec          int64
x_cord            float64
y cord            float64
Latitude          float64
Longitude         float64
vic_age_group       int64
 vic_cast           int64
vic_sex             int64
city_name           int64
police_station    float64
crime_level         int64
crime_code          int64
crime_name          int64
result            float64
dtype: object
            cmp_no  cmp_dt_day  cmp_dt_month  cmp_dt_year  cmp_tm_hr  \
1738820  402959896          21             1         2020         16
218287   925190358          10             9         2010          0
7313417  199655660          29             1         2012         22
1399693  209995553           8            11         2020         18
6032095  361421774          13            10         2009         22
6667199  710156570           3             7         2006         13
4540720  700771149          12             4         2008         15
1420422  272139917          25            10         2020         19
4095421  908682910           6             1         2015         16
4330038  781092785          31            12         2009         10
1398869  120922746           8             4         2016         11
3159447  619117823          20            12         2012          4
3142319  363935579           1             9         2013          1
7387090  490919626          26            12         2018         21
2334878  136408261          17             8         2016         11
285012   210590135          27             5         2019         10
297432   393862739          24             5         2019         12
4187617  905671500          11            10         2011          2
1611799  185241648          26             5         2020          5
355134   196442994           6             4         2019          1
3890167  502740350           1            10         2014          0
7350674  253773197           2            10         2017          8
5025294  904600135          26             9         2011         12
244830   147002741          25             6         2019         15
4414487  653449962          17             9         2007         19
7382975  773136240          19             8         2018          6
3895811  562478464          29             4         2013          8
1061197  229636743          15             4         2014         19
7152905  456337972          11             6         2008         14
2407861  181344427          13            10         2013         17
4903145  387549704          22             9         2007         17
4792643  920045837          12             3         2007          9
1345209  565138324          31            12         2011          8
152187   765879755           1             9         2019         16
5520852  976988180          13             1         2009          0
4362883  238295466          29             7         2008         17
4247118  615701579          29            11         2006         22
2931389  776216921           9             3         2013          4
5795934  743562532           8            10         2009          9
5989857  844981807          30             4         2008         17
6656682  851488668          20            11         2006         21
7231824  544795504           1             2         2017         10
4253847  521357265          10             6         2011         16
4821049  841728482          27             2         2006         18
2999621  238530461          20             6         2015          4
1987209  378049096          30             5         2014         22
6420370  461203033           3             5         2006         17
4628703  774883316           8             2         2007          0
657697   406146621          27             7         2021         14
3327532  670841978          31            10         2016         15
1607729  198672860          30             5         2020          1
7556996  374262788          29             5         2018         10
4539897  833216167          16             5         2008         17
1079718  618367221          29             5         2017         15
2429984  422124795          31             5         2017         13
4096503  896064891          19             8         2014         13
600474   402623420          21             9         2021          5
4260677  774333254          28            10         2007         17
6512296  929528406          31            10         2009          2
6351554  739328996           1             5         2010          0

         cmp_tm_min  cmp_tm_sec     x_cord    y cord   Latitude  Longitude  \
1738820          30           0  1005772.0  169554.0  40.632045 -73.922462
218287            0           0   989668.0  225399.0  40.785351 -73.980437
7313417          56           0  1041888.0  187383.0  40.680820 -73.792192
1399693          30           0   988554.0  216447.0  40.760781 -73.984465
6032095          30           0  1014057.0  192677.0  40.695489 -73.892511
6667199          45           0   985071.0  190331.0  40.689100 -73.997041
4540720          30           0  1040576.0  189540.0  40.686749 -73.796905
1420422          20           0  1036732.0  207396.0  40.735783 -73.810626
4095421          25           0  1014160.0  239740.0  40.824664 -73.891930
4330038           0           0  1023337.0  262851.0  40.888061 -73.858637
1398869          50           0   997056.0  197009.0  40.707420 -73.953812
3159447          43           0   998692.0  182460.0  40.667484 -73.947942
3142319           0           0  1004786.0  252793.0  40.860518 -73.925761
7387090           9           0   981350.0  158625.0  40.602073 -74.010445
2334878           0           0   990784.0  149362.0  40.576646 -73.976480
285012           10           0   995734.0  197465.0  40.708673 -73.958580
297432           15           0  1007424.0  239937.0  40.825225 -73.916268
4187617           0           0   986596.0  201225.0  40.719001 -73.991538
1611799           0           0  1006284.0  190177.0  40.688649 -73.920550
355134            4           0   984623.0  172738.0  40.640811 -73.998657
3890167           0           0  1006489.0  190021.0  40.688221 -73.919812
7350674          30           0  1013619.0  238885.0  40.822319 -73.893889
5025294          50           0  1055270.0  158051.0  40.600213 -73.744254
244830           30           0  1033448.0  206254.0  40.732668 -73.822484
4414487           0           0  1002051.0  245311.0  40.839988 -73.935668
7382975          30           0  1007164.0  231653.0  40.802488 -73.917236
3895811          30           0   992713.0  228110.0  40.792790 -73.969438
1061197          50           0  1002481.0  158288.0  40.601130 -73.934350
7152905          20           0   993134.0  175183.0  40.647517 -73.967987
2407861          55           0  1008133.0  247451.0  40.845847 -73.913680
4903145          30           0  1018124.0  257774.0  40.874148 -73.877516
4792643          25           0   987168.0  213465.0  40.752596 -73.989470
1345209          30           0  1014604.0  238800.0  40.822083 -73.890330
152187           20           0  1017542.0  255919.0  40.869059 -73.879630
5520852          30           0  1002253.0  248117.0  40.847689 -73.934930
4362883           0           0   953334.0  143646.0  40.560905 -74.111266
4247118          30           0  1001946.0  184888.0  40.674142 -73.936206
2931389          15           0  1021302.0  213563.0  40.752788 -73.866269
5795934           0           0  1053650.0  158969.0  40.602746 -73.750078
5989857           7           0  1038690.0  197089.0  40.707481 -73.803644
6656682          38           0  1005068.0  182616.0  40.667899 -73.924958
7231824          30           0  1008163.0  183416.0  40.670087 -73.913799
4253847          30           0   983246.0  176654.0  40.651559 -74.003620
4821049          30           0  1002264.0  250414.0  40.853993 -73.934884
2999621          40           0  1002253.0  248117.0  40.847689 -73.934930
1987209           0           0  1000555.0  230994.0  40.800694 -73.941109
6420370          30           0  1018455.0  241320.0  40.828985 -73.876404
4628703           1           0  1012839.0  270311.0  40.908577 -73.896573
657697           30           0   999920.0  180759.0  40.662813 -73.943520
3327532           0           0  1007649.0  243339.0  40.834562 -73.915443
1607729           5           0   997507.0  170528.0  40.634735 -73.952237
7556996          35           0  1006160.0  248680.0  40.849225 -73.920807
4539897           6           0  1021760.0  189151.0  40.685781 -73.864752
1079718           0           0   989793.0  211571.0  40.747397 -73.979997
2429984          50           0  1030622.0  216271.0  40.760177 -73.832612
4096503          30           0   986787.0  157922.0  40.600144 -73.990866
600474           23           0   992029.0  213332.0  40.752228 -73.971925
4260677          50           0   993063.0  216978.0  40.762235 -73.968188
6512296           0           0   990690.0  210145.0  40.743482 -73.976761
6351554           1           0  1041749.0  196938.0  40.707047 -73.792612

         vic_age_group   vic_cast  vic_sex  city_name  police_station  \
1738820              2          1        1          3            63.0
218287               0          4        1          2            20.0
7313417              1          3        0          0           113.0
1399693              0          1        1          2            18.0
6032095              2          0        1          0           104.0
6667199              2          3        1          3            76.0
4540720              0          1        1          0           113.0
1420422              1          0        1          0           107.0
4095421              1          1        1          1            41.0
4330038              4          1        1          1            47.0
1398869              2          2        1          3            90.0
3159447              0          1        1          3            71.0
3142319              2          0        0          2            34.0
7387090              0          3        0          3            62.0
2334878              0          3        1          3            60.0
285012               0          4        0          3            90.0
297432               2          0        0          1            44.0
4187617              0          4        1          2             5.0
1611799              0          1        1          3            83.0
355134               2          3        0          3            66.0
3890167              1          1        0          3            81.0
7350674              3          1        0          1            41.0
5025294              0          1        0          0           101.0
244830               2          3        0          0           107.0
4414487              2          3        0          2            33.0
7382975              0          0        0          1            40.0
3895811              2          3        1          2            24.0
1061197              3          3        0          3            61.0
7152905              0          4        1          3            70.0
2407861              2          1        1          1            46.0
4903145              2          2        0          1            52.0
4792643              0          3        1          2            14.0
1345209              4          2        0          1            41.0
152187               3          0        0          1            52.0
5520852              0          2        0          2            33.0
4362883              2          3        1          4           122.0
4247118              0          1        0          3            77.0
2931389              0          0        1          0           115.0
5795934              2          1        0          0           101.0
5989857              0          1        1          0           107.0
6656682              1          1        1          3            77.0
7231824              0          1        0          3            73.0
4253847              1          0        0          3            72.0
4821049              0          2        0          2            34.0
2999621              1          1        0          2            33.0
1987209              0          1        0          2            25.0
6420370              1          1        0          1            43.0
4628703              0          1        1          1            50.0
657697               0          1        1          3            71.0
3327532              1          0        1          1            44.0
1607729              0          0        1          3            70.0
7556996              4          2        0          1            46.0
4539897              2          4        1          0           102.0
1079718              0          1        0          2            17.0
2429984              0          4        1          0           109.0
4096503              4          3        0          3            62.0
600474               2          3        0          2            17.0
4260677              0          1        0          2            17.0
6512296              1          3        1          2            17.0
6351554              3          1        0          0           103.0

         crime_level  crime_code  crime_name  result
1738820            0         578           0     1.0
218287             0         578           0     1.0
7313417            2         361           3     1.0
1399693            2         348          13     1.0
6032095            1         110          10     1.0
6667199            1         107           6     1.0
4540720            2         344           5     1.0
1420422            2         351          11     1.0
4095421            2         351          11     1.0
4330038            1         107           6     1.0
1398869            2         352          22     1.0
3159447            2         361           3     1.0
3142319            2         344           5     1.0
7387090            0         578           0     1.0
2334878            2         344           5     1.0
285012             1         109          12     1.0
297432             2         344           5     1.0
4187617            2         341           2     1.0
1611799            2         341           2     1.0
355134             1         126          15     1.0
3890167            1         109          12     1.0
7350674            0         578           0     1.0
5025294            1         126          15     1.0
244830             0         578           0     1.0
4414487            2         351          11     1.0
7382975            1         106           4     1.0
3895811            2         352          22     1.0
1061197            2         341           2     1.0
7152905            2         341           2     1.0
2407861            2         344           5     1.0
4903145            2         359          21     1.0
4792643            0         578           0     1.0
1345209            1         109          12     1.0
152187             1         116           8     1.0
5520852            0         578           0     1.0
4362883            1         107           6     1.0
4247118            1         126          15     1.0
2931389            1         109          12     1.0
5795934            1         126          15     1.0
5989857            0         578           0     1.0
6656682            1         106           4     1.0
7231824            0         578           0     1.0
4253847            2         361           3     1.0
4821049            1         121          11     1.0
2999621            1         106           4     1.0
1987209            1         121          11     1.0
6420370            2         361           3     1.0
4628703            2         341           2     1.0
657697             1         106           4     1.0
3327532            1         109          12     1.0
1607729            1         114          19     1.0
7556996            1         126          15     1.0
4539897            2         344           5     1.0
1079718            1         107           6     1.0
2429984            0         578           0     1.0
4096503            2         341           2     1.0
600474             2         344           5     1.0
4260677            1         109          12     1.0
6512296            1         109          12     1.0
6351554            1         104           7     1.0

In [8]:
d_copy.to_csv('output.csv', index=False)

In [9]:
d = pd.read_csv('/content/output.csv') 
print(d)

            cmp_no  cmp_dt_day  cmp_dt_month  cmp_dt_year  cmp_tm_hr  \
0        509837549          15            12         2019         18
1        134037758          26            12         2019         20
2        855385879          26            12         2019         19
3        241602326          25            12         2019         23
4        249276017          20            12         2019         14
...            ...         ...           ...          ...        ...
5142657  744350707          17            12         2018          3
5142658  380927470           5             6         2018         23
5142659  502083804          10             2         2018          8
5142660  609916130          11            12         2018          7
5142661  766425924          10             5         2018         11

         cmp_tm_min  cmp_tm_sec     x_cord    y cord   Latitude  Longitude  \
0                45           0  1034178.0  209758.0  40.742281 -73.819824
1                 0           0  1054394.0  162186.0  40.611570 -73.747365
2                57           0  1007027.0  245405.0  40.840234 -73.917684
3                 0           0   987147.0  220853.0  40.772875 -73.989542
4                 0           0  1008690.0  238862.0  40.822271 -73.911698
...             ...         ...        ...       ...        ...        ...
5142657           0           0  1026486.0  262591.0  40.887333 -73.847250
5142658          30           0  1018029.0  240747.0  40.827414 -73.877946
5142659          30           0  1010861.0  243330.0  40.834528 -73.903836
5142660          30           0  1001322.0  235045.0  40.811812 -73.938329
5142661          30           0  1016138.0  214586.0  40.755616 -73.884903

         vic_age_group   vic_cast  vic_sex  city_name  police_station  \
0                    0          0        0          0           109.0
1                    0          0        0          0           101.0
2                    1          1        0          1            44.0
3                    2          1        1          2            20.0
4                    3          2        1          1            42.0
...                ...        ...      ...        ...             ...
5142657              0          0        0          1            47.0
5142658              0          1        1          1            43.0
5142659              2          1        0          1            42.0
5142660              3          1        1          2            32.0
5142661              0          0        0          0           115.0

         crime_level  crime_code  crime_name  result
0                  0         578           0     1.0
1                  2         341           2     1.0
2                  2         361           3     1.0
3                  2         341           2     1.0
4                  1         106           4     1.0
...              ...         ...         ...     ...
5142657            2         348          13     1.0
5142658            1         110          10     1.0
5142659            2         341           2     1.0
5142660            2         344           5     1.0
5142661            2         341           2     1.0

[5142662 rows x 20 columns]

In [10]:
d_copy = d.copy()
d_copy.drop(columns=['cmp_no'], inplace=True)

d_copy.drop(columns=['cmp_tm_sec'], inplace=True)
d_copy.drop(columns=['result'], inplace=True)
print(d_copy)

         cmp_dt_day  cmp_dt_month  cmp_dt_year  cmp_tm_hr  cmp_tm_min  \
0                15            12         2019         18          45
1                26            12         2019         20           0
2                26            12         2019         19          57
3                25            12         2019         23           0
4                20            12         2019         14           0
...             ...           ...          ...        ...         ...
5142657          17            12         2018          3           0
5142658           5             6         2018         23          30
5142659          10             2         2018          8          30
5142660          11            12         2018          7          30
5142661          10             5         2018         11          30

            x_cord    y cord   Latitude  Longitude  vic_age_group   vic_cast  \
0        1034178.0  209758.0  40.742281 -73.819824              0          0
1        1054394.0  162186.0  40.611570 -73.747365              0          0
2        1007027.0  245405.0  40.840234 -73.917684              1          1
3         987147.0  220853.0  40.772875 -73.989542              2          1
4        1008690.0  238862.0  40.822271 -73.911698              3          2
...            ...       ...        ...        ...            ...        ...
5142657  1026486.0  262591.0  40.887333 -73.847250              0          0
5142658  1018029.0  240747.0  40.827414 -73.877946              0          1
5142659  1010861.0  243330.0  40.834528 -73.903836              2          1
5142660  1001322.0  235045.0  40.811812 -73.938329              3          1
5142661  1016138.0  214586.0  40.755616 -73.884903              0          0

         vic_sex  city_name  police_station  crime_level  crime_code  \
0              0          0           109.0            0         578
1              0          0           101.0            2         341
2              0          1            44.0            2         361
3              1          2            20.0            2         341
4              1          1            42.0            1         106
...          ...        ...             ...          ...         ...
5142657        0          1            47.0            2         348
5142658        1          1            43.0            1         110
5142659        0          1            42.0            2         341
5142660        1          2            32.0            2         344
5142661        0          0           115.0            2         341

         crime_name
0                 0
1                 2
2                 3
3                 2
4                 4
...             ...
5142657          13
5142658          10
5142659           2
5142660           5
5142661           2

[5142662 rows x 17 columns]

In [36]:

X = d_copy.iloc[:50000, :15]  
y = d_copy.iloc[:50000, 15:] 


X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [38]:
X_train

,cmp_dt_day,cmp_dt_month,cmp_dt_year,cmp_tm_hr,cmp_tm_min,x_cord,y cord,Latitude,Longitude,vic_age_group,vic_cast,vic_sex,city_name,police_station,crime_level
39087,12,11,2019,7,25,997097.0,210380.0,40.744120,-73.953639,0,3,0,0,108.0,2
30893,22,11,2019,8,30,1059279.0,214945.0,40.756341,-73.729184,3,1,1,0,111.0,0
45278,2,11,2019,11,0,1018828.0,213182.0,40.751753,-73.875201,2,0,0,0,115.0,2
16398,20,12,2019,20,30,1006895.0,237886.0,40.819597,-73.918187,2,0,0,1,40.0,2
13653,13,12,2019,9,31,1034504.0,152593.0,40.585374,-73.819074,2,3,1,0,100.0,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11284,16,12,2019,20,17,1004214.0,251507.0,40.856989,-73.927832,2,0,0,2,34.0,0
44732,4,11,2019,18,20,1003372.0,248278.0,40.848128,-73.930885,1,0,1,2,34.0,2
38158,14,11,2019,13,30,1023964.0,149259.0,40.576277,-73.857040,0,3,0,0,100.0,1
860,16,12,2019,15,30,1000285.0,187730.0,40.681946,-73.942188,0,0,0,3,79.0,1
15795,14,12,2019,8,30,1003974.0,235187.0,40.812196,-73.928748,1,0,1,1,40.0,2

In [39]:
model = tf.keras.Sequential([tf.keras.layers.Input(input_shape=(2,)),
                         tf.keras.layers.Dense(64, activation='relu'),
                         tf.keras.layers.Dense(64, activation='relu'),
                         tf.keras.layers.Dense(2)])


model.compile(optimizer='adam',
              loss= tf.keras.losses.SparseCategoricalCrossentropy(), 
              metrics=['accuracy'])

In [40]:
#y_train_encoded = tf.keras.utils.to_categorical(y_train)
model.fit(X_test, y_test, epochs=10)


predictions = model.predict(X_test)


y_test_encoded = tf.keras.utils.to_categorical(y_test)
loss, accuracy = model.evaluate(X_test, y_test_encoded)


print("Loss:", loss)
print("Accuracy:", accuracy)

Epoch 1/10

ValueError: ignored